version: '3'

services:
  app:
    image: node:18
    working_dir: /workspaces/testdevcontainers/packages/server
    command: yarn dev
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://root:r00tp4skalF10@mongo:27017/admin
      - MAIL_URL=smtp://mail:1025
    volumes:
      - ..:/workspaces/testdevcontainers
    deploy:
      restart_policy:
        condition: on-failure
    links:
      - mongo
      - mail

  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    volumes:
      - ./.docker/mongo/data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=r00tp4skalF10

  mail:
    image: maildev/maildev
    ports:
      - 1025:1025
      - 1080:1080